#!/usr/bin/env sh

set -ex

# from https://keys.openpgp.org/
KEY_ID=730878BE36688D52
gpg --recv ${KEY_ID}
gpg --armor --export ${KEY_ID} | apt-key add

echo "deb https://s3-us-west-1.amazonaws.com/repo.socialtag.tv/beta/ vankman main" > /etc/apt/sources.list.d/socialtag.list
apt-get -y update
apt-get -y install socialtag-raspberry-system

THE_NEW_HOSTNAME=$(cat /sys/class/net/eth0/address | tr -d ':')
echo ${THE_NEW_HOSTNAME} > /etc/hostname
echo "127.0.0.1 ${THE_NEW_HOSTNAME}" >> /etc/hosts

systemctl disable wpa_supplicant.service

echo "LS0tIDEwLXdwYV9zdXBwbGljYW50Lm9yaWcJMjAyMC0wMi0xNyAxODo1MzoyMi45NzU5NTk5MzcgLTA1MDAKKysrIDEwLXdwYV9zdXBwbGljYW50CTIwMjAtMDItMTcgMTg6NTk6NTguNDkxNDE1MTE1IC0wNTAwCkBAIC01OSw3ICs1OSw3IEBACiAJc3lzbG9nIGluZm8gInN0YXJ0aW5nIHdwYV9zdXBwbGljYW50IgogCXdwYV9zdXBwbGljYW50X2RyaXZlcj0iJHt3cGFfc3VwcGxpY2FudF9kcml2ZXI6LW5sODAyMTEsd2V4dH0iCiAJZHJpdmVyPSR7d3BhX3N1cHBsaWNhbnRfZHJpdmVyOistRH0kd3BhX3N1cHBsaWNhbnRfZHJpdmVyCi0JZXJyPSQod3BhX3N1cHBsaWNhbnQgLUIgLWMiJHdwYV9zdXBwbGljYW50X2NvbmYiIC1pIiRpbnRlcmZhY2UiIFwKKwllcnI9JCh3cGFfc3VwcGxpY2FudCAtdSAtQiAtYyIkd3BhX3N1cHBsaWNhbnRfY29uZiIgLWkiJGludGVyZmFjZSIgXAogCSAgICAiJGRyaXZlciIgMj4mMSkKIAllcnJuPSQ/CiAJaWYgWyAkZXJybiAhPSAwIF07IHRoZW4K" | base64 --decode > 10-wpa_supplicant.patch

patch /lib/dhcpcd/dhcpcd-hooks/10-wpa_supplicant 10-wpa_supplicant.patch

echo "LS0tIGNvbmZpZy50eHQub3JpZwkyMDIwLTAyLTE3IDE4OjQ3OjUzLjA2MzIxMTUxMyAtMDUwMAorKysgY29uZmlnLnR4dAkyMDIwLTAyLTE3IDE4OjQ4OjM1LjkxMTQwMjE3OCAtMDUwMApAQCAtMjIsNyArMjIsNyBAQAogI2ZyYW1lYnVmZmVyX2hlaWdodD03MjAKIAogIyB1bmNvbW1lbnQgaWYgaGRtaSBkaXNwbGF5IGlzIG5vdCBkZXRlY3RlZCBhbmQgY29tcG9zaXRlIGlzIGJlaW5nIG91dHB1dAotI2hkbWlfZm9yY2VfaG90cGx1Zz0xCitoZG1pX2ZvcmNlX2hvdHBsdWc9MQogCiAjIHVuY29tbWVudCB0byBmb3JjZSBhIHNwZWNpZmljIEhETUkgbW9kZSAodGhpcyB3aWxsIGZvcmNlIFZHQSkKICNoZG1pX2dyb3VwPTEKQEAgLTMwLDcgKzMwLDcgQEAKIAogIyB1bmNvbW1lbnQgdG8gZm9yY2UgYSBIRE1JIG1vZGUgcmF0aGVyIHRoYW4gRFZJLiBUaGlzIGNhbiBtYWtlIGF1ZGlvIHdvcmsgaW4KICMgRE1UIChjb21wdXRlciBtb25pdG9yKSBtb2RlcwotI2hkbWlfZHJpdmU9MgoraGRtaV9kcml2ZT0yCiAKICMgdW5jb21tZW50IHRvIGluY3JlYXNlIHNpZ25hbCB0byBIRE1JLCBpZiB5b3UgaGF2ZSBpbnRlcmZlcmVuY2UsIGJsYW5raW5nLCBvcgogIyBubyBkaXNwbGF5CkBAIC01Nyw5ICs1NywxMCBAQAogZHRwYXJhbT1hdWRpbz1vbgogCiBbcGk0XQotIyBFbmFibGUgRFJNIFZDNCBWM0QgZHJpdmVyIG9uIHRvcCBvZiB0aGUgZGlzcG1hbnggZGlzcGxheSBzdGFjawotZHRvdmVybGF5PXZjNC1ma21zLXYzZAogbWF4X2ZyYW1lYnVmZmVycz0yCitoZG1pX2ZvcmNlX2hvdHBsdWc6MD0xCitoZG1pX2dyb3VwOjA9MQoraGRtaV9tb2RlOjA9NAogCiBbYWxsXQogI2R0b3ZlcmxheT12YzQtZmttcy12M2QK" | base64 --decode > config.txt.patch

patch /boot/config.txt config.txt.patch
